apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hostpvclaim
  labels:
    app: jenkins
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
